import {
  LucideLayoutDashboard,
  LucideUsers,
  LucideUser,
  LucideUserCog,
  LucideListOrdered,
  LucideClipboardCheck,
  LucideCar,
  LucideSettings,
  LucideOctagonAlert,
  LucideBell,
  LucideSearch,
  LucideBan,
  LucideMenu,
  LucidePlus,
  LucideEye,
  LucidePencil,
  LucideTrash2,
  LucideFileUp,
  LucideHouse,
  LucideSave,
  LucideLock,
  LucideLogOut,
  LucideLockOpen,
  LucideTriangleAlert,
  LucideClock,
  LucideKeyRound,
  LucideChevronRight,
  LucideChevronLeft,
  LucideChevronDown,
  LucideArrowDownToLine,
  LucidePrinter,
  LucideLoaderCircle ,
  LucideCheck,
  LucideX,
  LucideClipboardList, 
  LucideCarTaxiFront
} from '@lucide/angular';

export const Icons = {
  LucideLayoutDashboard,
  LucideUsers,
  LucideUser,  
  LucideUserCog,
  LucideListOrdered,
  LucideClipboardCheck,
  LucideCar,
  LucideSettings,
  LucideOctagonAlert,
  LucideBell,
  LucideSearch,
  LucideBan,
  LucideClock, 
  LucidePlus,
  LucideEye,
  LucidePencil,
  LucideTrash2,
  LucideFileUp,
  LucideKeyRound, 
  LucideHouse,
  LucideSave, 
  LucideTriangleAlert,
  LucideLock, 
  LucideLockOpen,
  LucideLogOut,
  LucideChevronRight,
  LucideChevronLeft,
  LucideChevronDown,
  LucideMenu,
  LucideArrowDownToLine,
  LucidePrinter ,
  LucideLoaderCircle ,
  LucideCheck,
  LucideX,
  LucideClipboardList,
  LucideCarTaxiFront, 
};